# Generated by Django 3.1.2 on 2022-04-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, choices=[('GP', 'GP'), ('MS', 'MS')], max_length=200, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=200, null=True)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, choices=[('Ville', 'Ville'), ('Campagne', 'Campagne')], max_length=200, null=True)),
                ('aggregated_notation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('studytime', models.CharField(blank=True, choices=[('Moins de 2h', 'Moins de 2h'), ('2 à 5 heures', '2 à 5 heures'), ('5 à 10 heures', '5 à 10 heures'), ('Plus de 10h', 'Plus de 10h')], max_length=200, null=True)),
                ('absences', models.IntegerField(default=0)),
                ('Dalc', models.IntegerField(default=0)),
                ('Medu', models.CharField(blank=True, choices=[('aucun', 'aucun'), ('brevet', 'brevet'), ('baccalaureat', 'baccalaureat'), ('bac à bac+2', 'bac à bac+2'), ('bac +3 et plus', 'bac +3 et plus')], max_length=200, null=True)),
                ('Fedu', models.CharField(blank=True, choices=[('aucun', 'aucun'), ('brevet', 'brevet'), ('baccalaureat', 'baccalaureat'), ('bac à bac+2', 'bac à bac+2'), ('bac +3 et plus', 'bac +3 et plus')], max_length=200, null=True)),
                ('health', models.IntegerField(default=0)),
                ('famrel', models.IntegerField(default=0)),
                ('famsup', models.CharField(blank=True, choices=[('no', 'no'), ('yes', 'yes')], max_length=200, null=True)),
            ],
        ),
    ]
