# Generated by Django 4.0.4 on 2022-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, choices=[(('GP', 'GP'), ('MS', 'MS'))], max_length=200, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=200, null=True)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, choices=[('U', 'U'), ('R', 'R')], max_length=200, null=True)),
                ('famsize', models.CharField(blank=True, choices=[('LE3', 'LE3'), ('GT3', 'GT3')], max_length=200, null=True)),
                ('Pstatus', models.CharField(blank=True, choices=[('LE3', 'LE3'), ('GT3', 'GT3')], max_length=200, null=True)),
                ('Medu', models.IntegerField(default=0)),
                ('Fedu', models.IntegerField(default=0)),
                ('Mjob', models.CharField(blank=True, choices=[('LE3', 'LE3'), ('GT3', 'GT3')], max_length=200, null=True)),
                ('Fjob', models.CharField(blank=True, choices=[('LE3', 'LE3'), ('GT3', 'GT3')], max_length=200, null=True)),
                ('reason', models.CharField(blank=True, choices=[('home', 'home'), ('reputation', 'reputation'), ('course', 'course'), ('other', 'other')], max_length=200, null=True)),
                ('guardian', models.CharField(blank=True, choices=[('mother', 'mother'), ('father', 'father'), ('other', 'other')], max_length=200, null=True)),
                ('traveltime', models.IntegerField(default=0)),
                ('studytime', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('schoolsup', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('famsup', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('paid', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('activities', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('nursery', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('higher', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('internet', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('romantic', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True)),
                ('famrel', models.IntegerField(default=0)),
                ('freetime', models.IntegerField(default=0)),
                ('goout', models.IntegerField(default=0)),
                ('Dalc', models.IntegerField(default=0)),
                ('Walc', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('absences', models.IntegerField(default=0)),
                ('G1', models.IntegerField(default=0)),
                ('G2', models.IntegerField(default=0)),
                ('G3', models.IntegerField(default=0)),
            ],
        ),
    ]
