# Generated by Django 4.0.4 on 2022-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Fjob',
            field=models.CharField(blank=True, choices=[('teacher', 'teacher'), ('health', 'health'), ('services', 'services'), ('at_home', 'at_home'), ('other', 'other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mjob',
            field=models.CharField(blank=True, choices=[('teacher', 'teacher'), ('health', 'health'), ('services', 'services'), ('at_home', 'at_home'), ('other', 'other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pstatus',
            field=models.CharField(blank=True, choices=[('T', 'T'), ('A', 'A')], max_length=200, null=True),
        ),
    ]
