# Generated by Django 3.1.2 on 2022-04-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220420_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='G3',
        ),
    ]
