# Generated by Django 3.1.2 on 2022-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_g3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='G3',
            field=models.IntegerField(default=0),
        ),
    ]
