# Generated by Django 3.1.2 on 2022-04-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_g3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Fjob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='G1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='G2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='G3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Mjob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Pstatus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Walc',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='student',
            name='failures',
        ),
        migrations.RemoveField(
            model_name='student',
            name='famsize',
        ),
        migrations.RemoveField(
            model_name='student',
            name='famsup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='freetime',
        ),
        migrations.RemoveField(
            model_name='student',
            name='goout',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='higher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nursery',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='student',
            name='romantic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolsup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='traveltime',
        ),
        migrations.AddField(
            model_name='student',
            name='aggregated_notation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fedu',
            field=models.CharField(blank=True, choices=[('aucun', 'aucun'), ('brevet', 'brevet'), ('baccalauréat', 'baccalauréat'), ('bac à bac+2', 'bac à bac+2'), ('bac +3 et plus', 'bac +3 et plus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Medu',
            field=models.CharField(blank=True, choices=[('aucun', 'aucun'), ('brevet', 'brevet'), ('baccalauréat', 'baccalauréat'), ('bac à bac+2', 'bac à bac+2'), ('bac +3 et plus', 'bac +3 et plus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, choices=[('Ville', 'Ville'), ('Campagne', 'Campagne')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('Féminin', 'Féminin'), ('Masculin', 'Masculin')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studytime',
            field=models.CharField(blank=True, choices=[('Moins de 2h', 'Moins de 2h'), ('2 à 5 heures', '2 à 5 heures'), ('5 à 10 heures', '5 à 10 heures'), ('Plus de 10h', 'Plus de 10h')], max_length=200, null=True),
        ),
    ]
